[default]
# Extend the default identifier checker with these additional words
extend-identifiers = { renamify = "renamify", styl = "styl" }

[files]
extend-exclude = [
  "target/",
  ".git/",
  "*.lock",
  "*.profraw",
  "*.profdata",
  # Test files that intentionally contain typos
  "**/test_*",
  "**/*_test*",
  "docs/src/content/docs/rename-vs-replace.mdx",
  "docs/src/content/docs/case-studies/deploy-requests-rename.mdx",
]

[type.rust]
extend-glob = ["*.rs"]

[type.toml]
extend-glob = ["*.toml"]

[type.markdown]
extend-glob = ["*.md"]
