# Cache: 2025-08-30 19:54:10
name: ShellCheck

on:
  push:
    paths:
      - "**.sh"
      - "**/scripts/**"
      - ".github/workflows/shellcheck.yml"
  pull_request:
    paths:
      - "**.sh"
      - "**/scripts/**"
      - ".github/workflows/shellcheck.yml"

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: ./scripts/shellcheck.sh
