# Cache: 2025-09-03 02:13:59
name: ShellCheck

on:
  push:
    branches: [main, master]
    paths:
      - "**.sh"
      - "**/scripts/**"
      - ".github/workflows/shellcheck.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "**.sh"
      - "**/scripts/**"
      - ".github/workflows/shellcheck.yml"

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: ./scripts/shellcheck.sh
