// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Detected style of an identifier or path segment
 */
declare type CoercionStyle =
	| "Snake"
	| "Kebab"
	| "Camel"
	| "Pascal"
	| "ScreamingSnake"
	| "Dot"
	| "Mixed";
