// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a single entry in the renaming history
 */
declare type HistoryEntry = {
	/**
	 * Unique identifier for this plan/operation
	 */
	id: string;
	/**
	 * Timestamp when the operation was performed
	 */
	created_at: string;
	/**
	 * Original identifier that was replaced
	 */
	search: string;
	/**
	 * New identifier that replaced the old one
	 */
	replace: string;
	/**
	 * Naming styles used for the transformation
	 */
	styles: Array<string>;
	/**
	 * Include patterns used for file filtering
	 */
	includes: Array<string>;
	/**
	 * Exclude patterns used for file filtering
	 */
	excludes: Array<string>;
	/**
	 * Files that were modified (path -> checksum after apply)
	 */
	affected_files: Record<string, string>;
	/**
	 * Renames that were performed (from -> to)
	 */
	renames: Array<[string, string]>;
	/**
	 * Path to the backup directory for this operation
	 */
	backups_path: string;
	/**
	 * If this is a revert operation, the ID of the operation being reverted
	 */
	revert_of?: string;
	/**
	 * If this is a redo operation, the ID of the original operation
	 */
	redo_of?: string;
};
