// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

declare type MatchHunk = {
	file: string;
	line: number;
	col: number;
	variant: string;
	content: string;
	replace: string;
	start: number;
	end: number;
	line_before?: string;
	line_after?: string;
	coercion_applied?: string;
	original_file?: string;
	renamed_file?: string;
	patch_hash?: string;
};
