// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

declare type PlanOptions = {
	includes: Array<string>;
	excludes: Array<string>;
	respect_gitignore: boolean;
	unrestricted_level: number;
	styles?: Array<Style>;
	rename_files: boolean;
	rename_dirs: boolean;
	rename_root: boolean;
	plan_out: string;
	coerce_separators: CoercionMode;
	exclude_match: Array<string>;
	exclude_matching_lines?: string;
	no_acronyms: boolean;
	include_acronyms: Array<string>;
	exclude_acronyms: Array<string>;
	only_acronyms: Array<string>;
};
