// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

declare type Plan = {
	id: string;
	created_at: string;
	search: string;
	replace: string;
	styles: Array<Style>;
	includes: Array<string>;
	excludes: Array<string>;
	matches: Array<MatchHunk>;
	paths: Array<Rename>;
	stats: Stats;
	version: string;
	created_directories?: Array<string>;
};
