// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

declare type Rename = {
	path: string;
	new_path: string;
	kind: RenameKind;
	coercion_applied?: string;
};
