// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

declare type Stats = {
	files_scanned: number;
	total_matches: number;
	matches_by_variant: Record<string, number>;
	files_with_matches: number;
};
