// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

declare type Style =
	| "Snake"
	| "Kebab"
	| "Camel"
	| "Pascal"
	| "ScreamingSnake"
	| "Title"
	| "Train"
	| "ScreamingTrain"
	| "Dot"
	| "Original";
